#the file for the gui using qt creator to make it.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 30, 461, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.square = QtWidgets.QWidget()
        self.square.setObjectName("square")
        self.s_areabutton = QtWidgets.QRadioButton(self.square)
        self.s_areabutton.setGeometry(QtCore.QRect(40, 30, 61, 21))
        self.s_areabutton.setObjectName("s_areabutton")
        self.s_perimeterbutton = QtWidgets.QRadioButton(self.square)
        self.s_perimeterbutton.setGeometry(QtCore.QRect(310, 30, 91, 20))
        self.s_perimeterbutton.setObjectName("s_perimeterbutton")
        self.side_label = QtWidgets.QLabel(self.square)
        self.side_label.setGeometry(QtCore.QRect(50, 120, 41, 21))
        self.side_label.setText("")
        self.side_label.setObjectName("side_label")
        self.s_output = QtWidgets.QLabel(self.square)
        self.s_output.setGeometry(QtCore.QRect(50, 240, 351, 61))
        self.s_output.setText("")
        self.s_output.setAlignment(QtCore.Qt.AlignCenter)
        self.s_output.setObjectName("s_output")
        self.s_sumbit = QtWidgets.QPushButton(self.square, clicked = lambda: self.submit())
        self.s_sumbit.setGeometry(QtCore.QRect(80, 320, 100, 32))
        self.s_sumbit.setObjectName("s_sumbit")
        self.s_clear = QtWidgets.QPushButton(self.square, clicked = lambda: self.clear())
        self.s_clear.setGeometry(QtCore.QRect(280, 320, 101, 32))
        self.s_clear.setObjectName("s_clear")
        self.side_input = QtWidgets.QLineEdit(self.square)
        self.side_input.setEnabled(False)
        self.side_input.setGeometry(QtCore.QRect(220, 120, 221, 21))
        self.side_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.side_input.setObjectName("side_input")
        self.s_calculate = QtWidgets.QPushButton(self.square, clicked = lambda: self.calculate())
        self.s_calculate.setGeometry(QtCore.QRect(160, 60, 100, 32))
        self.s_calculate.setObjectName("s_calculate")
        self.tabWidget.addTab(self.square, "")
        self.triangle = QtWidgets.QWidget()
        self.triangle.setObjectName("triangle")
        self.t_areabutton = QtWidgets.QRadioButton(self.triangle)
        self.t_areabutton.setGeometry(QtCore.QRect(40, 30, 61, 21))
        self.t_areabutton.setObjectName("t_areabutton")
        self.t_perimeterbutton = QtWidgets.QRadioButton(self.triangle)
        self.t_perimeterbutton.setGeometry(QtCore.QRect(310, 30, 91, 20))
        self.t_perimeterbutton.setObjectName("t_perimeterbutton")
        self.t_calculate = QtWidgets.QPushButton(self.triangle, clicked = lambda: self.calculate())
        self.t_calculate.setGeometry(QtCore.QRect(160, 60, 100, 32))
        self.t_calculate.setObjectName("t_calculate")
        self.side1_label = QtWidgets.QLabel(self.triangle)
        self.side1_label.setGeometry(QtCore.QRect(50, 110, 41, 16))
        self.side1_label.setText("")
        self.side1_label.setObjectName("side1_label")
        self.side2_label = QtWidgets.QLabel(self.triangle)
        self.side2_label.setGeometry(QtCore.QRect(50, 150, 41, 16))
        self.side2_label.setText("")
        self.side2_label.setObjectName("side2_label")
        self.side3_label = QtWidgets.QLabel(self.triangle)
        self.side3_label.setGeometry(QtCore.QRect(50, 190, 41, 16))
        self.side3_label.setText("")
        self.side3_label.setObjectName("side3_label")
        self.side1_input = QtWidgets.QLineEdit(self.triangle)
        self.side1_input.setEnabled(False)
        self.side1_input.setGeometry(QtCore.QRect(220, 110, 221, 21))
        self.side1_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.side1_input.setObjectName("side1_input")
        self.side2_input = QtWidgets.QLineEdit(self.triangle)
        self.side2_input.setEnabled(False)
        self.side2_input.setGeometry(QtCore.QRect(220, 150, 221, 21))
        self.side2_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.side2_input.setObjectName("side2_input")
        self.side3_input = QtWidgets.QLineEdit(self.triangle)
        self.side3_input.setEnabled(False)
        self.side3_input.setGeometry(QtCore.QRect(220, 190, 221, 21))
        self.side3_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.side3_input.setObjectName("side3_input")
        self.t_output = QtWidgets.QLabel(self.triangle)
        self.t_output.setGeometry(QtCore.QRect(50, 240, 351, 61))
        self.t_output.setText("")
        self.t_output.setAlignment(QtCore.Qt.AlignCenter)
        self.t_output.setObjectName("t_output")
        self.t_sumbit = QtWidgets.QPushButton(self.triangle, clicked = lambda: self.submit())
        self.t_sumbit.setGeometry(QtCore.QRect(80, 320, 100, 32))
        self.t_sumbit.setObjectName("t_sumbit")
        self.t_clear = QtWidgets.QPushButton(self.triangle, clicked = lambda: self.clear())
        self.t_clear.setGeometry(QtCore.QRect(280, 320, 100, 32))
        self.t_clear.setObjectName("t_clear")
        self.tabWidget.addTab(self.triangle, "")
        self.rectangle = QtWidgets.QWidget()
        self.rectangle.setObjectName("rectangle")
        self.r_areabutton = QtWidgets.QRadioButton(self.rectangle)
        self.r_areabutton.setGeometry(QtCore.QRect(40, 30, 61, 21))
        self.r_areabutton.setObjectName("r_areabutton")
        self.r_perimeterbutton = QtWidgets.QRadioButton(self.rectangle)
        self.r_perimeterbutton.setGeometry(QtCore.QRect(310, 30, 91, 20))
        self.r_perimeterbutton.setObjectName("r_perimeterbutton")
        self.r_calculate = QtWidgets.QPushButton(self.rectangle, clicked = lambda: self.calculate())
        self.r_calculate.setGeometry(QtCore.QRect(160, 60, 100, 32))
        self.r_calculate.setObjectName("r_calculate")
        self.width_label = QtWidgets.QLabel(self.rectangle)
        self.width_label.setGeometry(QtCore.QRect(50, 120, 41, 16))
        self.width_label.setText("")
        self.width_label.setObjectName("width_label")
        self.length_label = QtWidgets.QLabel(self.rectangle)
        self.length_label.setGeometry(QtCore.QRect(50, 160, 51, 16))
        self.length_label.setText("")
        self.length_label.setObjectName("length_label")
        self.width_input = QtWidgets.QLineEdit(self.rectangle)
        self.width_input.setEnabled(False)
        self.width_input.setGeometry(QtCore.QRect(220, 120, 221, 21))
        self.width_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.width_input.setObjectName("width_input")
        self.length_input = QtWidgets.QLineEdit(self.rectangle)
        self.length_input.setEnabled(False)
        self.length_input.setGeometry(QtCore.QRect(220, 160, 221, 21))
        self.length_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.length_input.setObjectName("length_input")
        self.r_output = QtWidgets.QLabel(self.rectangle)
        self.r_output.setGeometry(QtCore.QRect(50, 240, 351, 61))
        self.r_output.setText("")
        self.r_output.setAlignment(QtCore.Qt.AlignCenter)
        self.r_output.setObjectName("r_output")
        self.r_sumbit = QtWidgets.QPushButton(self.rectangle, clicked = lambda: self.submit())
        self.r_sumbit.setGeometry(QtCore.QRect(80, 320, 100, 32))
        self.r_sumbit.setObjectName("r_sumbit")
        self.r_clear = QtWidgets.QPushButton(self.rectangle, clicked = lambda: self.clear())
        self.r_clear.setGeometry(QtCore.QRect(280, 320, 100, 32))
        self.r_clear.setObjectName("r_clear")
        self.tabWidget.addTab(self.rectangle, "")
        self.ciricle = QtWidgets.QWidget()
        self.ciricle.setObjectName("ciricle")
        self.c_areabutton = QtWidgets.QRadioButton(self.ciricle)
        self.c_areabutton.setGeometry(QtCore.QRect(40, 30, 61, 21))
        self.c_areabutton.setObjectName("c_areabutton")
        self.c_perimeterbutton = QtWidgets.QRadioButton(self.ciricle)
        self.c_perimeterbutton.setGeometry(QtCore.QRect(310, 30, 91, 20))
        self.c_perimeterbutton.setObjectName("c_perimeterbutton")
        self.c_calculate = QtWidgets.QPushButton(self.ciricle, clicked = lambda: self.calculate())
        self.c_calculate.setGeometry(QtCore.QRect(160, 60, 100, 32))
        self.c_calculate.setObjectName("c_calculate")
        self.radius_label = QtWidgets.QLabel(self.ciricle)
        self.radius_label.setGeometry(QtCore.QRect(50, 120, 51, 16))
        self.radius_label.setText("")
        self.radius_label.setObjectName("radius_label")
        self.radius_input = QtWidgets.QLineEdit(self.ciricle)
        self.radius_input.setEnabled(False)
        self.radius_input.setGeometry(QtCore.QRect(220, 120, 221, 21))
        self.radius_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.radius_input.setObjectName("radius_input")
        self.c_output = QtWidgets.QLabel(self.ciricle)
        self.c_output.setGeometry(QtCore.QRect(50, 240, 351, 61))
        self.c_output.setText("")
        self.c_output.setAlignment(QtCore.Qt.AlignCenter)
        self.c_output.setObjectName("c_output")
        self.c_sumbit = QtWidgets.QPushButton(self.ciricle, clicked = lambda: self.submit())
        self.c_sumbit.setGeometry(QtCore.QRect(80, 320, 100, 32))
        self.c_sumbit.setObjectName("c_sumbit")
        self.c_clear = QtWidgets.QPushButton(self.ciricle, clicked = lambda: self.clear())
        self.c_clear.setGeometry(QtCore.QRect(280, 320, 100, 32))
        self.c_clear.setObjectName("c_clear")
        self.tabWidget.addTab(self.ciricle, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shape Calculator"))
        self.s_areabutton.setText(_translate("MainWindow", "Area"))
        self.s_perimeterbutton.setText(_translate("MainWindow", "Perimeter"))
        self.s_sumbit.setText(_translate("MainWindow", "Submit"))
        self.s_clear.setText(_translate("MainWindow", "Clear"))
        self.s_calculate.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.square), _translate("MainWindow", "square"))
        self.t_areabutton.setText(_translate("MainWindow", "Area"))
        self.t_perimeterbutton.setText(_translate("MainWindow", "Perimeter"))
        self.t_calculate.setText(_translate("MainWindow", "Calculate"))
        self.t_sumbit.setText(_translate("MainWindow", "Submit"))
        self.t_clear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.triangle), _translate("MainWindow", "triangle"))
        self.r_areabutton.setText(_translate("MainWindow", "Area"))
        self.r_perimeterbutton.setText(_translate("MainWindow", "Perimeter"))
        self.r_calculate.setText(_translate("MainWindow", "Calculate"))
        self.r_sumbit.setText(_translate("MainWindow", "Submit"))
        self.r_clear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rectangle), _translate("MainWindow", "rectangle"))
        self.c_areabutton.setText(_translate("MainWindow", "Area"))
        self.c_perimeterbutton.setText(_translate("MainWindow", "Perimeter"))
        self.c_calculate.setText(_translate("MainWindow", "Calculate"))
        self.c_sumbit.setText(_translate("MainWindow", "Submit"))
        self.c_clear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ciricle), _translate("MainWindow", "circle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
